-- ============================================================================
-- Mavlers.ai — Rebuild the Services page to match the latest design brief.
-- Replaces the Services page sections with: hero, services_detail (12 rich
-- service blocks + quick-jump), foundations grid, delivery process, an
-- implementations CTA band, and the final CTA.
-- Safe to re-run (deletes + reinserts this page's sections).
-- ============================================================================

delete from public.page_sections
where page_id = (select id from public.pages where slug = 'services');

insert into public.page_sections (page_id, type, sort_order, content)
select id, v.type, v.ord, v.content::jsonb from public.pages, (values

  ('hero', 1, $json${"animated":false,"badge":"AI & Automation Engineering Services","heading_html":"The engineering capability behind <span>your AI and automation ideas.</span>","subhead":"You bring the industry knowledge and the opportunity — as an agency serving clients, or a brand solving your own problems. We bring a senior team that architects, builds, integrates and ships production-grade AI. Below is what we do, and how we do it.","primary_cta":{"label":"Discuss Your Requirement","href":"/book-a-call"},"secondary_cta":{"label":"View Our Implementations","href":"/implementations"}}$json$),

  ('services_detail', 2, $json${"cta_primary":{"label":"Connect with an AI expert","href":"/book-a-call"},"cta_secondary":{"label":"Submit a project brief","href":"/book-a-call"},"items":[
    {"id":"rag","short":"RAG Agents","mono":"RAG","cat":"Knowledge Intelligence","title":"RAG Agent Development","tagline":"Agents that answer from your own trusted, access-controlled knowledge — with citations, not hallucinations.","build":["Retrieval-augmented assistants over documents, wikis, tickets and databases","Citation-backed answers that link to the exact source passage","Access-controlled retrieval that respects user roles and permissions","Ingestion pipelines that keep the knowledge base continuously fresh"],"detail":["Chunking, embeddings and hybrid (semantic + keyword) retrieval","Re-ranking and query rewriting to lift answer precision","Vector store setup (pgvector, Pinecone, Weaviate) with metadata filters","Evaluation harness for groundedness, relevance and hallucination rate"],"stack":["pgvector","Pinecone","LangChain","OpenAI / Claude"],"outcome":"Staff and customers get fast, trustworthy answers from your content — cutting search time and support load."},
    {"id":"workflow","short":"Workflow Automation","mono":"WF","cat":"Automation","title":"Workflow Automation","tagline":"Remove manual, repetitive work by wiring your tools into reliable, observable automations.","build":["Event- and schedule-driven workflows across your existing stack","Data sync, enrichment and notification pipelines","Reporting and document-generation automations","Human-in-the-loop steps where judgement is required"],"detail":["Built in n8n, Make or Langflow — self-hosted where needed","Idempotent steps, retries and dead-letter handling for reliability","Secrets management and scoped API credentials per connection","Run logging and alerting so failures surface immediately"],"stack":["n8n","Make","Langflow","Webhooks"],"outcome":"Hours of manual effort disappear each week, with fewer errors and a clear audit trail."},
    {"id":"api","short":"API Integration","mono":"API","cat":"Integrations","title":"API & Platform Integration","tagline":"Connect the platforms your business runs on into one dependable flow of data and actions.","build":["Two-way integrations between SaaS platforms, apps and databases","Custom connectors for systems without off-the-shelf support","Real-time (webhook) and batch synchronisation patterns","Data mapping, transformation and validation layers"],"detail":["REST, GraphQL and webhook integrations with OAuth2 / API-key auth","Rate-limit handling, pagination and backoff strategies","Schema contracts and validation to prevent bad data propagating","Monitoring, retries and reconciliation for eventual consistency"],"stack":["REST","GraphQL","OAuth2","Webhooks"],"outcome":"Systems stay in sync automatically, eliminating copy-paste and data drift between tools."},
    {"id":"orchestration","short":"Orchestration","mono":"ORC","cat":"Automation","title":"Multi-System Orchestration","tagline":"Coordinate data and actions across many platforms so disconnected systems behave as one.","build":["Orchestration layers that sequence steps across multiple systems","Stateful, long-running processes with checkpoints and recovery","Conditional branching, parallelism and fan-out / fan-in flows","Central visibility into every process instance and its status"],"detail":["Queue- and event-driven architecture for decoupled reliability","State machines / workflow engines for resumable execution","Observability: tracing, metrics and per-step logs","Compensation logic to safely roll back partial failures"],"stack":["Queues","Event bus","State machines","Observability"],"outcome":"Complex cross-platform processes run reliably end to end, without manual coordination."},
    {"id":"bpa","short":"Process Automation","mono":"BPA","cat":"Automation","title":"Business Process Automation","tagline":"Automate approvals, routing, reporting and document handling — with control where it matters.","build":["Approval and routing workflows with role-based decision points","Document processing: extraction, classification and filing","Case and request management automations","Scheduled reporting and reconciliation jobs"],"detail":["OCR and structured extraction from PDFs, forms and emails","Business rules engine for routing and eligibility logic","Human approval gates with full audit logging","SLA timers, escalations and exception handling"],"stack":["OCR","Rules engine","n8n","Cloud functions"],"outcome":"Back-office processes move faster and more consistently, with people focused on exceptions, not busywork."},
    {"id":"custom-ai","short":"Custom AI Apps","mono":"AI","cat":"AI Engineering","title":"Custom AI Application Development","tagline":"Bespoke AI applications, copilots and intelligent interfaces built around a specific need.","build":["Full-stack AI web apps, portals and internal tools","Copilots and assistants embedded into existing products","Streaming chat interfaces with tools, memory and history","Admin, analytics and feedback dashboards"],"detail":["Modern front end (React / Next.js) with streaming responses","Prompt orchestration, function calling and structured output","Auth, multi-tenancy and usage metering built in","Cost, latency and quality monitoring per feature"],"stack":["Next.js","React","Node / Python","LLM APIs"],"outcome":"A production-grade AI product your users actually adopt — not a fragile prototype."},
    {"id":"agents","short":"AI Agents","mono":"AG","cat":"AI Engineering","title":"AI Agent Development","tagline":"Tool-enabled agents — single or multi-agent — that complete real business tasks end to end.","build":["Goal-driven agents that plan, call tools and act","Multi-agent systems with specialised roles and coordination","Human approval and guardrails for sensitive actions","Persistent memory and context across sessions"],"detail":["Tool/function schemas with strict input validation","Planning loops with step limits, timeouts and fallbacks","Observability: full trace of reasoning, tool calls and outcomes","Evaluation and regression testing on task success rate"],"stack":["LangGraph","Function calling","MCP","Vector memory"],"outcome":"Repetitive, multi-step work gets handled autonomously — with humans in control of what matters."},
    {"id":"llm","short":"LLM Integration","mono":"LLM","cat":"AI Engineering","title":"LLM Integration","tagline":"Integrate and route between leading models with cost, latency and quality controls built in.","build":["Model integration into apps, workflows and backends","Provider-agnostic routing across OpenAI, Anthropic and open models","Prompt management, versioning and A/B testing","Guardrails, moderation and PII handling"],"detail":["Model routing by task, cost and latency budgets","Caching and batching to control token spend","Structured output with schema validation and retries","Fallback chains for provider outages or rate limits"],"stack":["OpenAI","Anthropic","Open models","Gateways"],"outcome":"The right model for each job — with predictable cost, quality and no single-vendor lock-in."},
    {"id":"mcp","short":"MCP","mono":"MCP","cat":"Integrations","title":"Model Context Protocol (MCP)","tagline":"Custom MCP servers and connectors that give agents secure, governed access to your tools and data.","build":["Custom MCP servers exposing your systems as agent tools","Connectors for internal APIs, databases and SaaS platforms","Scoped, permissioned access for what agents can see and do","Reusable tool catalogues across multiple AI products"],"detail":["MCP tool/resource definitions with typed schemas","Auth, scoping and per-tool authorisation policies","Audit logging of every tool invocation","Versioning and backward compatibility for tools"],"stack":["MCP","TypeScript / Python","OAuth","RBAC"],"outcome":"Agents gain safe, standardised access to your systems — reusable across every future AI build."},
    {"id":"crm-erp","short":"CRM & ERP","mono":"CRM","cat":"Integrations","title":"CRM & ERP Integration","tagline":"Deep, dependable integrations with the systems of record you run your business on.","build":["Bi-directional sync with Salesforce, HubSpot, Dynamics and more","ERP integration for orders, inventory, finance and operations","AI features layered onto CRM/ERP data (scoring, drafting, insights)","Data hygiene, de-duplication and enrichment automations"],"detail":["Native APIs, bulk endpoints and change-data-capture where available","Field mapping, conflict resolution and sync-loop prevention","Sandbox-first delivery with staged rollout to production","Respect for platform limits, governor rules and permissions"],"stack":["Salesforce","HubSpot","Dynamics","ERP APIs"],"outcome":"Your systems of record stay clean, connected and enriched — ready for AI to add value on top."},
    {"id":"poc","short":"Proof of Concept","mono":"PoC","cat":"Advisory","title":"AI Proof of Concept","tagline":"Validate technical and business feasibility quickly, against real data, before committing budget.","build":["Focused PoC targeting the single riskiest assumption","Working demo on representative data, not slideware","Clear success criteria agreed up front","Findings, limitations and a recommended path to production"],"detail":["Rapid architecture spike with the real integration points","Quantitative evaluation against defined metrics","Cost and latency projections at production scale","Go / no-go decision brief with trade-offs documented"],"stack":["Rapid prototyping","Eval harness","Real data"],"outcome":"A confident, evidence-based decision on whether and how to build — in weeks, not months."},
    {"id":"mvp","short":"MVP","mono":"MVP","cat":"Product Engineering","title":"MVP Development","tagline":"Turn a validated concept into a launch-ready product — with senior oversight, not just AI-generated code.","build":["Scoped, launch-ready product with the essential features","UX, engineering, integrations, testing and deployment","Analytics and feedback loops from day one","A pragmatic roadmap to scale after validation"],"detail":["AI-accelerated build paired with senior code review","Security review, testing and CI/CD before launch","Cloud deployment with monitoring and error tracking","Documentation and handover, or ongoing partnership"],"stack":["Next.js","Python","Cloud","CI/CD"],"outcome":"A dependable product in market fast — built to be maintained and scaled, not thrown away."}
  ]}$json$),

  ('feature_grid', 3, $json${"eyebrow":"Across every engagement","heading":"The engineering foundations we bring to all of it","columns":4,"items":[{"title":"Security by design","body":"Role-based access, scoped credentials, data isolation and audit logging."},{"title":"Human-in-the-loop","body":"Approval gates and guardrails wherever judgement or risk demands them."},{"title":"Observability","body":"Tracing, logging and evaluation so you can see and trust what runs."},{"title":"Technology agnostic","body":"We pick the right models and tools for the job, not a fixed stack."},{"title":"Production-grade","body":"Testing, CI/CD and monitoring — engineered to run, not just to demo."},{"title":"Data governance","body":"PII handling, retention controls and responsible-AI practices."},{"title":"Flexible engagement","body":"Work with us directly, or as a behind-the-scenes delivery partner."},{"title":"Ongoing support","body":"Maintenance, optimization and model updates after launch."}]}$json$),

  ('process_timeline', 4, $json${"eyebrow":"How we deliver","heading":"A consistent path from problem to production","steps":[{"n":"1","title":"Opportunity discussion"},{"n":"2","title":"Business & technical discovery"},{"n":"3","title":"Solution blueprint"},{"n":"4","title":"Prototype / proof of concept"},{"n":"5","title":"Implementation"},{"n":"6","title":"Integration & testing"},{"n":"7","title":"Launch"},{"n":"8","title":"Optimization & support"}]}$json$),

  ('cta_band', 5, $json${"variant":"band","heading":"See these services in action","body":"Browse real implementation patterns across industries and the digital lifecycle — the workflows, agents and integrations we build.","ctas":[{"label":"View Our Implementations →","href":"/implementations","style":"primary"}]}$json$),

  ('cta_band', 6, $json${"variant":"final","heading":"Have a service requirement in mind?","body":"Tell us the problem or the capability you want to build. We'll map it to the right approach and team.","ctas":[{"label":"Book a Call","href":"/book-a-call","style":"primary"},{"label":"Or submit a requirement →","href":"/book-a-call","style":"link"}]}$json$)

) as v(type, ord, content)
where public.pages.slug = 'services';
