-- ============================================================================
-- Mavlers.ai — homepage re-seed for the reference design.
-- Idempotent: clears the homepage (slug '') sections and re-inserts the full
-- reference-accurate set (adds opportunity "tags" + a dedicated
-- `implementations` section). Safe to re-run.
-- ============================================================================

delete from public.page_sections
where page_id = (select id from public.pages where slug = '');

insert into public.page_sections (page_id, type, sort_order, content)
select id, v.type, v.ord, v.content::jsonb from public.pages, (values
  ('hero', 1, $json${"animated":true,"badge":"AI & automation engineering","heading_html":"Turn deep industry expertise into <span>working AI solutions.</span>","subhead":"Whether you're an agency serving clients in a specific industry or a brand building automation directly, we architect, build and scale production-grade AI and automation with your team — backed by 15+ years of digital delivery.","primary_cta":{"label":"Book a Call","href":"/book-a-call","style":"primary"},"secondary_cta":{"label":"Learn more","href":"/services","style":"link"},"trust_items":["Agencies & brands","Production-ready engineering","Flexible teams","Secure by default"]}$json$),
  ('stats_bar', 2, $json${"stats":[{"num":"15+","label":"years of digital delivery"},{"num":"500+","label":"agency relationships"},{"num":"52+","label":"countries served"},{"num":"80+","label":"AI-enabled developers"},{"num":"10","label":"AI technology consultants"},{"num":"1000s","label":"projects delivered"}],"logos_title":"The platforms agencies already build on","logos":["Salesforce","HubSpot","Marketo","Braze","Microsoft","Zendesk","Shopify","n8n"]}$json$),
  ('feature_grid', 3, $json${"eyebrow":"The agency opportunity","heading":"AI opportunities are everywhere. The capability to build them isn't.","columns":3,"items":[{"n":"01","tag":"The demand","title":"Demand is moving faster than internal capability","body":"Teams are spotting valuable AI use cases every week — but rarely have the specialized engineers to actually ship them into production."},{"n":"02","tag":"The cost","title":"Building an internal AI team is expensive","body":"Recruitment, experimentation, architecture, security and ongoing model changes all demand serious, sustained investment few can justify."},{"n":"03","tag":"The fit","title":"Most AI vendors don't understand your context","body":"You need a delivery partner that respects your domain, your standards and — when relevant — your client relationships."}],"callout":{"text":"Mavlers.ai gives agencies and brands the engineering capability to ship AI — without building a separate team.","cta":{"label":"Start the conversation","href":"/book-a-call"}}}$json$),
  ('partnership', 4, $json${"eyebrow":"The partnership model","heading":"Your expertise. Our engineering. One solution.","left_title":"You bring","left_items":["Industry knowledge","Business context","The opportunity","Strategic direction","Client & brand ownership"],"right_title":"Mavlers.ai delivers","right_items":["Opportunity validation","Solution architecture","UX & prototyping","AI engineering","Automation workflows","System integration","QA & deployment","Maintenance & scaling"]}$json$),
  ('service_capabilities', 5, $json${"eyebrow":"What we build","heading":"Engineering capabilities, ready to deploy under your brand","link":{"label":"Explore all services →","href":"/services"},"items":[{"mono":"AI","title":"Custom AI Development","body":"Bespoke AI applications, copilots and intelligent interfaces built for your client."},{"mono":"RAG","title":"RAG & Knowledge Systems","body":"Retrieval-augmented assistants grounded in your client's own trusted content."},{"mono":"AG","title":"AI Agents","body":"Tool-enabled agents that complete real business tasks end to end."},{"mono":"WF","title":"Workflow Automation","body":"n8n, Make and Langflow automations that remove manual, repetitive work."},{"mono":"OR","title":"AI Orchestration","body":"Coordinated multi-agent and multi-model workflows with observability."},{"mono":"MCP","title":"MCP Development","body":"Custom Model Context Protocol servers and connectors for secure tool access."},{"mono":"API","title":"API & Platform Integration","body":"Connect CRMs, ERPs, LLMs and custom APIs into one orchestrated system."},{"mono":"MVP","title":"AI-Powered MVP Development","body":"Validate and launch AI products faster with disciplined engineering."}]}$json$),
  ('connect_grid', 6, $json${"eyebrow":"What we can connect","heading":"Every system your client already runs","subhead":"We orchestrate data and workflows across the tools your clients depend on — turning disconnected platforms into one intelligent ecosystem.","items":["Websites","CRMs","ERPs","Marketing Automation","Analytics","Customer Support","Email Platforms","Cloud Storage","Knowledge Bases","Databases","LLM Providers","Custom APIs"]}$json$),
  ('implementations', 7, $json${"eyebrow":"Implementations","heading":"AI in action across industries and the digital lifecycle","subhead":"Explore the workflows, agents and integrations we build for agency clients — from marketing and sales to support, operations and internal productivity.","cta":{"label":"Explore Our Implementations","href":"/implementations"}}$json$),
  ('engagement_models', 8, $json${"eyebrow":"Engagement models","heading":"Start where it makes sense for your team","items":[{"step":"01","title":"Discovery & Feasibility","body":"For teams with an opportunity or client problem that needs validation.","featured":false},{"step":"02","title":"Proof of Concept","body":"For quickly validating the technical and business feasibility of a solution.","featured":false},{"step":"03","title":"Project-Based Implementation","body":"For defined AI, automation or integration requirements.","featured":false},{"step":"04","title":"Dedicated AI Delivery Pod","body":"For agencies and brands that want an embedded, scalable AI delivery team.","featured":true}]}$json$),
  ('process_timeline', 9, $json${"eyebrow":"Delivery process","heading":"From client opportunity to production deployment","subhead":"A clear, milestone-based roadmap — from first conversation to a live, supported deployment under your brand.","steps":[{"n":"1","title":"Opportunity discussion"},{"n":"2","title":"Business & technical discovery"},{"n":"3","title":"Solution blueprint"},{"n":"4","title":"Prototype / proof of concept"},{"n":"5","title":"Implementation"},{"n":"6","title":"Integration & testing"},{"n":"7","title":"Go-live launch"},{"n":"8","title":"Optimization & support"}]}$json$),
  ('pillars', 10, $json${"eyebrow":"Why teams choose Mavlers.ai","heading":"A delivery partner built around how you actually work","items":[{"title":"Senior AI engineering","body":"A team of AI-enabled developers and technology consultants, not generalists learning on your dime."},{"title":"Flexible engagement","body":"Work with us directly or as a behind-the-scenes delivery partner under your brand."},{"title":"Secure by default","body":"Security, privacy and compliance considered from architecture through deployment."},{"title":"Flexible engagement","body":"From a single proof of concept to an embedded, scalable AI delivery pod."},{"title":"Global delivery scale","body":"15+ years serving 500+ agencies across 52+ countries, with thousands of projects delivered."},{"title":"Ongoing support","body":"Optimization, maintenance and scaling as models, tools and your clients evolve."}]}$json$),
  ('cta_band', 11, $json${"variant":"final","heading":"Have an AI opportunity? Let's build it.","body":"Book a call with our team to validate your idea, scope a proof of concept, or plan a dedicated AI delivery pod for your team.","ctas":[{"label":"Book a Call","href":"/book-a-call","style":"primary"},{"label":"Explore Services","href":"/services","style":"outline"}]}$json$)
) as v(type, ord, content)
where public.pages.slug = '';
